from turtle import Turtle, Screen
timy = Turtle()
print(timy)
timy.shape("turtle")
timy.color("red")
timy.forward(100)
timy.backward(50)
my_screen = Screen()
print(my_screen.canvheight)
my_screen.exitonclick()
